table Dim_Category
	column CategoryID
		dataType: int64
		summarizeBy: sum
		sourceColumn: CategoryID
		displayFolder: 'Keys'
		annotation Description = 'Primary key for Dim Category.'

	column CategoryName
		dataType: string
		summarizeBy: none
		sourceColumn: CategoryName
		displayFolder: 'Attributes'
		annotation Description = 'Categoryname in Dim Category.'

	column Description
		dataType: string
		summarizeBy: none
		sourceColumn: Description
		displayFolder: 'Attributes'
		annotation Description = 'Description in Dim Category.'

	column Vendor
		dataType: string
		summarizeBy: none
		sourceColumn: Vendor
		annotation Description = 'Vendor in Dim Category.'

	column SortOrder
		dataType: int64
		summarizeBy: sum
		sourceColumn: SortOrder
		annotation Description = 'Sortorder in Dim Category.'

	partition Dim_Category = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Dim_Category.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"
