table Fact_Pipeline_SampleData
	column PipelineID
		dataType: int64
		summarizeBy: sum
		sourceColumn: PipelineID
		displayFolder: 'Keys'
		annotation Description = 'Primary key for Fact Pipeline Sampledata.'

	column PipelineName
		dataType: string
		summarizeBy: none
		sourceColumn: PipelineName
		displayFolder: 'Attributes'
		annotation Description = 'Pipelinename in Fact Pipeline Sampledata.'

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		displayFolder: 'Attributes'
		annotation Description = 'Category in Fact Pipeline Sampledata.'

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		displayFolder: 'Attributes'
		annotation Description = 'Status in Fact Pipeline Sampledata.'

	column ScheduledStart
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ScheduledStart
		displayFolder: 'Measures'
		formatString: 'yyyy-MM-dd'
		annotation Description = 'Scheduledstart in Fact Pipeline Sampledata.'

	column ActualStart
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ActualStart
		displayFolder: 'Measures'
		formatString: 'yyyy-MM-dd'
		annotation Description = 'Actualstart in Fact Pipeline Sampledata.'

	column ScheduledEnd
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ScheduledEnd
		displayFolder: 'Measures'
		formatString: 'yyyy-MM-dd'
		annotation Description = 'Scheduledend in Fact Pipeline Sampledata.'

	column ActualEnd
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ActualEnd
		displayFolder: 'Measures'
		formatString: 'yyyy-MM-dd'
		annotation Description = 'Actualend in Fact Pipeline Sampledata.'

	column SLAHours
		dataType: decimal
		summarizeBy: sum
		sourceColumn: SLAHours
		displayFolder: 'Measures'
		annotation Description = 'Slahours in Fact Pipeline Sampledata.'

	column DurationHours
		dataType: decimal
		summarizeBy: sum
		sourceColumn: DurationHours
		displayFolder: 'Measures'
		formatString: '0.00%'
		annotation Description = 'Measure attribute for Fact Pipeline Sampledata.'

	column StartDelayMinutes
		dataType: int64
		summarizeBy: sum
		sourceColumn: StartDelayMinutes
		displayFolder: 'Measures'
		annotation Description = 'Startdelayminutes in Fact Pipeline Sampledata.'

	column EndDelayMinutes
		dataType: int64
		summarizeBy: sum
		sourceColumn: EndDelayMinutes
		annotation Description = 'Enddelayminutes in Fact Pipeline Sampledata.'

	column SLAStatus
		dataType: string
		summarizeBy: none
		sourceColumn: SLAStatus
		displayFolder: 'Attributes'
		annotation Description = 'Slastatus in Fact Pipeline Sampledata.'

	column Environment
		dataType: string
		summarizeBy: none
		sourceColumn: Environment
		displayFolder: 'Measures'
		annotation Description = 'Environment in Fact Pipeline Sampledata.'

	column Owner
		dataType: string
		summarizeBy: none
		sourceColumn: Owner
		displayFolder: 'Measures'
		annotation Description = 'Owner in Fact Pipeline Sampledata.'

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		annotation Description = 'Region in Fact Pipeline Sampledata.'

	column RetryCount
		dataType: int64
		summarizeBy: sum
		sourceColumn: RetryCount
		displayFolder: 'Measures'
		formatString: '#,##0'
		annotation Description = 'Measure attribute for Fact Pipeline Sampledata.'

	partition Fact_Pipeline_SampleData = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Fact_Pipeline_SampleData.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"
